# Generated by Django 6.0.7 on 2026-08-01 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Lab A - Computer Science Building', max_length=100, unique=True)),
                ('building_location', models.CharField(help_text='e.g. Block B, Floor 2', max_length=150)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum total workstations in this lab')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the lab is currently operational')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.PositiveIntegerField(help_text='Unique seat index within the lab, e.g. 1, 2, 3...')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', help_text='Operational state of the workstation', max_length=20)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to='labs.lab')),
            ],
            options={
                'ordering': ['lab', 'seat_number'],
                'unique_together': {('lab', 'seat_number')},
            },
        ),
    ]
