# Generated by Django 6.0.7 on 2026-08-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the lab facility is currently operational'),
        ),
    ]
