# Generated by Django 6.0.7 on 2026-08-01 21:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('labs', '0002_alter_lab_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='e.g. Morning Slot 1 (08:00 - 10:00)', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_bookings', to='academics.course')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_bookings', to='labs.lab')),
                ('lecturer', models.ForeignKey(limit_choices_to={'role': 'LECTURER'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_bookings', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_bookings', to='labs.timeslot')),
            ],
            options={
                'ordering': ['date', 'time_slot__start_time'],
                'unique_together': {('lab', 'date', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='WorkstationReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='labs.timeslot')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='labs.workstation')),
            ],
            options={
                'ordering': ['date', 'time_slot__start_time'],
                'unique_together': {('workstation', 'date', 'time_slot')},
            },
        ),
    ]
