# Generated by Django 6.0.7 on 2026-08-02 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_maintenanceticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workstationreservation',
            constraint=models.UniqueConstraint(fields=('student', 'date', 'time_slot'), name='unique_student_reservation_per_slot'),
        ),
    ]
